import { useState } from 'react'

const STAGES = [
  { id: 'training-data', label: 'Training data' },
  { id: 'tokenize', label: 'Pattern learning' },
  { id: 'predict', label: 'Prediction' },
  { id: 'context', label: 'Your context' },
]

// ---- Stage 1: is this training data? ---------------------------------
const TRAINING_ITEMS = [
  {
    label: 'A Reddit comment thread from 6 years ago',
    isTraining: true,
    note: 'Reddit has sold data access for training under licensing deals — but plenty was also scraped before those deals existed.',
  },
  {
    label: 'A pirated ebook scraped without permission',
    isTraining: true,
    note: 'Often included in practice — the subject of major ongoing lawsuits, not a clean "no."',
  },
  {
    label: 'A painting photographed and posted to a museum website',
    isTraining: true,
    note: 'Images, not just text, get pulled into training sets for multimodal models — copyright status of the art itself doesn’t stop the photo from being scraped.',
  },
  {
    label: 'A private company’s internal Slack messages that later leaked online',
    isTraining: true,
    note: 'Once it’s publicly indexed somewhere, scraping generally can’t tell it apart from anything else public — the leak, not the original privacy, ends up mattering.',
  },
  {
    label: 'A celebrity deepfake video posted to a forum',
    isTraining: true,
    note: 'Disputed and messy — companies claim to filter this out, but enforcement is inconsistent and it has turned up in datasets before.',
  },
  {
    label: 'Synthetic data generated by another AI model',
    isTraining: true,
    note: 'Increasingly common in newer models — and some researchers warn it can quietly degrade quality over generations ("model collapse").',
  },
  {
    label: 'A textbook published two weeks after the training cutoff',
    isTraining: false,
    note: 'If it’s after the cutoff, it can’t have been seen — timing matters more than content.',
  },
  {
    label: 'A blog post the author deleted the same day it was published, before search engines cached it',
    isTraining: false,
    note: 'Speed matters as much as publicness. If it’s gone before any crawler passes by, brief public existence still isn’t enough.',
  },
  {
    label: 'A customer support message saved on a company’s private computer — you’d need an API key to see it',
    isTraining: false,
    note: 'An API key is like a password that lets one computer program talk to another and pull specific data — it’s not a public webpage anyone can stumble onto. Without one, there’s nothing for a scraper to grab.',
  },
  {
    label: 'A journal you keep in a desk drawer, later transcribed into a private, access-locked family history app',
    isTraining: false,
    note: 'Digitized isn’t the same as public. Access-locked and never indexed means it still sits outside anything a scraper could reach — digitization alone doesn’t create exposure.',
  },
]

function TrainingDataStage() {
  const [index, setIndex] = useState(0)
  const [guess, setGuess] = useState(null)
  const [sortedCount, setSortedCount] = useState(0)
  const item = TRAINING_ITEMS[index]
  const isLast = index === TRAINING_ITEMS.length - 1
  const correct = guess !== null && guess === item.isTraining

  const pick = (guessTraining) => {
    if (guess !== null) return
    setGuess(guessTraining)
    setSortedCount((c) => c + 1)
  }

  const next = () => {
    setGuess(null)
    setIndex((i) => (isLast ? 0 : i + 1))
  }

  return (
    <div>
      <p className="flow-intro">
        AI models are trained on huge amounts of text — books, articles, websites, conversations.
        This is where all its "knowledge" of patterns comes from, frozen at whatever point
        training stopped. Fair warning: several of these are genuinely disputed even among people
        who study this professionally.
      </p>
      <p className="ks-widget__prompt">{item.label}</p>
      {guess === null ? (
        <div className="ks-widget__options">
          <button type="button" className="ks-widget__option" onClick={() => pick(true)}>
            Training data
          </button>
          <button type="button" className="ks-widget__option" onClick={() => pick(false)}>
            Not training data
          </button>
        </div>
      ) : (
        <div className={`ks-widget__reveal ${correct ? 'is-correct' : 'is-off'}`}>
          <p className="ks-widget__reveal-head">
            {correct ? 'Correct —' : 'Not quite —'} {item.isTraining ? 'training data.' : 'not training data.'}
          </p>
          <p>{item.note}</p>
          <button type="button" className="btn btn--ghost" onClick={next}>
            {isLast ? 'Start over' : 'Next example'}
            <span className="arrow">&rarr;</span>
          </button>
        </div>
      )}
      <p className="ks-widget__progress">
        {sortedCount} of {TRAINING_ITEMS.length} sorted
      </p>
      <p className="illus-note">Explanatory notes are simplified for teaching — not legal or technical guidance.</p>
    </div>
  )
}

// ---- Stage 2: tokenize + nearest-neighbor demo -------------------------
const TOKENS = ['The', 'inch', 'worm', 'ate', 'a', 'leaf', '.']
const TOKEN_NEIGHBORS = {
  The: [['a', 62], ['this', 21], ['that', 11], ['some', 6]],
  inch: [['foot', 34], ['centimeter', 28], ['tiny', 20], ['measurement', 18]],
  worm: [['caterpillar', 41], ['insect', 26], ['snake', 18], ['bug', 15]],
  ate: [['devoured', 38], ['munched', 27], ['nibbled', 21], ['consumed', 14]],
  a: [['the', 58], ['an', 24], ['one', 12], ['some', 6]],
  leaf: [['leaves', 37], ['plant', 25], ['tree', 22], ['grass', 16]],
  '.': [['.', 100]],
}

function ProbabilityBars({ title, rows }) {
  return (
    <div className="ks-prob">
      <p className="ks-prob__title">{title}</p>
      {rows.map(([word, pct]) => (
        <div className="ks-prob__row" key={word}>
          <span className="ks-prob__word">{word}</span>
          <span className="ks-prob__track">
            <span className="ks-prob__fill" style={{ width: `${pct}%` }} />
          </span>
          <span className="ks-prob__pct">{pct}%</span>
        </div>
      ))}
      <p className="illus-note">Illustrative — not real model outputs.</p>
    </div>
  )
}

function TokenizeStage() {
  const [tokenized, setTokenized] = useState(false)
  const [selected, setSelected] = useState(null)

  return (
    <div>
      <p className="flow-intro">
        During training, the model learns statistical patterns — which words, ideas, and
        structures tend to follow others. It isn’t memorizing facts like a filing cabinet; it’s
        learning relationships.
      </p>
      <p className="ks-tok__sentence">&ldquo;The inchworm ate a leaf.&rdquo;</p>
      {!tokenized ? (
        <button type="button" className="btn btn--ghost" onClick={() => setTokenized(true)}>
          Tokenize this sentence <span className="arrow">&rarr;</span>
        </button>
      ) : (
        <>
          <div className="ks-tok__tokens">
            {TOKENS.map((t) => (
              <button
                key={t}
                type="button"
                className={`ks-tok__chip ${TOKEN_NEIGHBORS[t]?.length > 1 ? 'is-clickable' : ''} ${
                  selected === t ? 'is-selected' : ''
                }`}
                onClick={() => TOKEN_NEIGHBORS[t]?.length > 1 && setSelected(t)}
              >
                {t}
              </button>
            ))}
          </div>
          <p className="ks-widget__progress">
            Notice "inchworm" split into two pieces, "inch" and "worm" — the tokenizer doesn’t know
            it’s one bug. Click a token to see what it’s positioned near in the model’s "meaning
            space."
          </p>
          {selected && (
            <ProbabilityBars
              title={`What "${selected}" sits closest to, in the model's learned sense of meaning:`}
              rows={TOKEN_NEIGHBORS[selected]}
            />
          )}
        </>
      )}
    </div>
  )
}

// ---- Stage 3: predict the next word ------------------------------------
const PREDICT_ROUNDS = [
  {
    label: 'Round 1 — what word comes next?',
    options: [
      { word: 'crawled', pct: 45 },
      { word: 'rested', pct: 25 },
      { word: 'disappeared', pct: 18 },
      { word: 'exploded', pct: 12, surprise: true },
    ],
  },
  {
    label: 'Round 2 — and now?',
    options: [
      { word: 'away', pct: 52 },
      { word: 'slowly', pct: 27 },
      { word: 'upward', pct: 13 },
      { word: 'sideways', pct: 8, surprise: true },
    ],
  },
  {
    label: 'Round 3 — one more.',
    options: [
      { word: 'into the grass.', pct: 48 },
      { word: 'onto another leaf.', pct: 31 },
      { word: 'and vanished.', pct: 21, surprise: true },
    ],
  },
]

function PredictStage() {
  const [round, setRound] = useState(0)
  const [chosen, setChosen] = useState([])
  const done = round >= PREDICT_ROUNDS.length

  const choose = (word) => {
    setChosen((prev) => [...prev, word])
    setRound((r) => r + 1)
  }

  const restart = () => {
    setChosen([])
    setRound(0)
  }

  return (
    <div>
      <p className="flow-intro">
        When you ask something, the model predicts the most likely next word, then the next, then
        the next — building a response one piece at a time based on the patterns it learned.
      </p>
      <p className="ks-tok__sentence">
        The inchworm ate a leaf and then... {chosen.join(' ')}
        {!done && <span className="ks-tok__cursor" aria-hidden="true" />}
      </p>
      {!done ? (
        <>
          <p className="ks-widget__progress">{PREDICT_ROUNDS[round].label}</p>
          <div className="ks-widget__quiz-options">
            {PREDICT_ROUNDS[round].options.map((o) => (
              <button
                key={o.word}
                type="button"
                className="ks-predict__option"
                onClick={() => choose(o.word)}
              >
                <span className="ks-predict__word">{o.word}</span>
                <span className="ks-prob__track">
                  <span className="ks-prob__fill" style={{ width: `${o.pct}%` }} />
                </span>
                <span className="ks-prob__pct">{o.pct}%</span>
              </button>
            ))}
          </div>
        </>
      ) : (
        <div className="ks-widget__reveal is-correct">
          <p>
            That’s the whole trick — one word at a time, each one just the most likely next piece,
            re-reading everything before every guess. Pick the lower-probability option next time
            and you’ll notice the sentence gets a little weirder, a little more "creative" — that’s
            what happens when a model is nudged toward less-likely tokens instead of always taking
            the safest one.
          </p>
          <button type="button" className="btn btn--ghost" onClick={restart}>
            Try again
          </button>
        </div>
      )}
      <p className="illus-note">Illustrative — not real model outputs.</p>
    </div>
  )
}

// ---- Stage 4: your context matters -------------------------------------
const CONTEXT_NEIGHBORS = {
  vague: [['It is', 34], ['Inchworms are', 29], ['There are', 22], ['This insect', 15]],
  specific: [['Fun fact:', 41], ['Here’s one:', 27], ['Did you know', 21], ['Great question —', 11]],
}
const CONTEXT_NOTES = {
  vague:
    'Vague input narrows down to a vague, generic-sounding opener — the model has no signal about who’s asking or why, so it defaults to the most generic pattern.',
  specific:
    'Specific, well-framed input steers it toward something actually useful — the audience and goal in the prompt shift what "likely next words" even means.',
}

function ContextStage() {
  const [mode, setMode] = useState('vague')
  return (
    <div>
      <p className="flow-intro">
        What you type shapes every one of those predictions. Vague input narrows down to a vague,
        generic-sounding answer. Specific, well-framed input steers it toward something actually
        useful.
      </p>
      <div className="ks-ctx__toggle">
        <button
          type="button"
          className={`ks-ctx__toggle-btn ${mode === 'vague' ? 'is-active' : ''}`}
          onClick={() => setMode('vague')}
        >
          <span className="ks-ctx__label">Vague</span>
          <span className="ks-ctx__prompt">&ldquo;Tell me about the inchworm.&rdquo;</span>
        </button>
        <button
          type="button"
          className={`ks-ctx__toggle-btn ${mode === 'specific' ? 'is-active' : ''}`}
          onClick={() => setMode('specific')}
        >
          <span className="ks-ctx__label">Specific</span>
          <span className="ks-ctx__prompt">
            &ldquo;I&rsquo;m a 3rd grade teacher. Give me one fun fact about inchworms I can share
            with my class.&rdquo;
          </span>
        </button>
      </div>
      <ProbabilityBars title="Likely next words the model would generate:" rows={CONTEXT_NEIGHBORS[mode]} />
      <p className="ks-ctx__note">{CONTEXT_NOTES[mode]}</p>
    </div>
  )
}

export default function HowItWorksFlow() {
  const [stageIndex, setStageIndex] = useState(0)
  const stage = STAGES[stageIndex]

  return (
    <div className="ks-widget ks-widget--flow">
      <div className="ks-loop__stages">
        {STAGES.map((s, i) => (
          <button
            key={s.id}
            type="button"
            className={`ks-loop__stage ${i === stageIndex ? 'is-active' : ''} ${i < stageIndex ? 'is-done' : ''}`}
            onClick={() => setStageIndex(i)}
          >
            {s.label}
          </button>
        ))}
      </div>
      <div className="ks-flow__panel">
        {stage.id === 'training-data' && <TrainingDataStage />}
        {stage.id === 'tokenize' && <TokenizeStage />}
        {stage.id === 'predict' && <PredictStage />}
        {stage.id === 'context' && <ContextStage />}
      </div>
      {stageIndex < STAGES.length - 1 && (
        <div className="ks-flow__next">
          <button type="button" className="btn btn--ghost" onClick={() => setStageIndex((i) => i + 1)}>
            Next stage: {STAGES[stageIndex + 1].label}
            <span className="arrow">&rarr;</span>
          </button>
        </div>
      )}
    </div>
  )
}
